package dev.hytalemodding.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import javax.annotation.Nonnull;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
public class LightingUI extends InteractiveCustomUIPage<LightingUI.BindingData> {

    public LightingUI(@Nonnull PlayerRef playerRef, @Nonnull CustomPageLifetime lifetime) {
        super(playerRef, lifetime, BindingData.CODEC);
    }


    public static class BindingData {
        public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)
                .addField(new KeyedCodec<>("@LightingColorPickerValue", Codec.STRING), (data, s)
                        -> data.LightingColorPickerValue = s, data -> data.LightingColorPickerValue)
                .build();

        public String LightingColorPickerValue;
    }

    @Override
    public void build(@Nonnull Ref<EntityStore> ref, @Nonnull UICommandBuilder uiCommandBuilder, @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {
        uiCommandBuilder.append("LightingPicker.ui");

        // var config = MyPlugin.getInstance().config.get();

        uiEventBuilder.addEventBinding(CustomUIEventBindingType.ValueChanged, "#LightingColorPickerValue",
                EventData.of("@LightingColorPickerValue", "#LightingColorPickerValue.Value"), false);

        uiCommandBuilder.set("#LightingColorPickerValue.Value", "FFFFFF"); // Set initial value for @LightingColorPickerValue

    }

    @Override
    public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @Nonnull BindingData data) {
        super.handleDataEvent(ref, store, data);
        boolean changed = false;


        if (data.LightingColorPickerValue != null) {
            // Logic for @LightingColorPickerValue
            this.playerRef.sendMessage(Message.raw("@LightingColorPickerValue updated to: " + data.LightingColorPickerValue));
            changed = true;
        }

        if (changed) {
            this.playerRef.sendMessage(Message.raw("Changes processed."));
        }
    }

}
